export const actionsType = {
  OPEN_MODEL: 'OPEN_MODEL',
  CLOSE_MODEL: 'CLOSE_MODEL',
  SHOW_CART_PRODUCT_COUNT: 'SHOW_CART_PRODUCT_COUNT',
  REMOVE_CART_PRODUCT: 'REMOVE_CART_PRODUCT',
  GET_ALL_CART_PRODUCT: 'GET_ALL_CART_PRODUCT',
  ADD_COUNT_PRODUCT: 'ADD_COUNT_PRODUCT',
};
